name: dart_design_patterns
description: The 23 GoF Design Patterns — explained and implemented in Dart.
version: 1.0.0

repository: https://github.com/ahmedm-gh/design-patterns-dart

environment:
  sdk: ^3.11.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.30.0
